apiVersion: apps/v1 # api版本号
kind: Deployment # 指定资源类型， Deployment 一次部署
metadata: # 指定资源的元信息，
  labels:
    app: redis
  name: saythx-redis # 资源名称
  namespace: work # 所属空间
spec: # 指定对资源的配置信息
  selector:
    matchLabels:
      app: redis
  replicas: 1 # 指定副本数量
  template:
    metadata:
      labels:
        app: redis
    spec: # 指定pod中容器的配置信息
      containers:
        - image: docker.io/bitnami/redis:7.4
          name: redis
          ports:
            - containerPort: 6379

---
# 作为service暴露出来

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: saythx-redis
  namespace: work
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: NodePort